spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db1?characterEncoding=utf8&useSSL=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    #properties.hibernate.hbm2ddl.auto: create-drop
    show-sql: true

logging:
  level:
    #org: error #暂时关闭日志干扰
    #com: error #暂时关闭日志干扰
    org.hibernate.SQL: debug #打印语句查看