logging:
  level: 
    com.example.demo: debug
    
# Spring
spring:
# ACTIVEMQ
  activemq:
    in-memory: true #本地测试可设置为true
#    broker-url: tcp://127.0.0.1:61616
#    password: admin
#    user: admin
#    packages:
#      trust-all: false
#      trusted:
#    pool:
#      enabled: false
      #configuration.*: 
#      expiry-timeout: 0
#      idle-timeout: 30000
#      max-connections: 1