logging:
  level: 
    com.example.demo: debug
    
# Spring
spring:
    activemq:
      in-memory: true #本地测试可设置为true
      #broker-url: tcp://127.0.0.1:61616
      #password: admin
      #user: admin
      send-timeout: 3000
      close-timeout: 3000
      packages:
        trust-all: true #消息支持传输及转换所有序列化对象，否则仅String
        #trusted:
      pool:
          enabled: true
          #连接池最大连接数
          max-connections: 10
          #强制的连接过期时间，与idleTimeout的区别在于：idleTimeout是在连接空闲一段时间失效，而expiryTimeout不管当前连接的情况，只要达到指定时间就失效。默认为0，never 
          expiry-timeout: 0
          #空闲的连接过期时间，默认为30秒
          idle-timeout: 30000
          reconnect-on-exception: true