logging:
  level: 
    com.example.demo: debug
    
# Spring
spring:
    activemq:
      in-memory: true #本地测试可设置为true
      #broker-url: tcp://127.0.0.1:61616
      #password: admin
      #user: admin
      send-timeout: 3000
      close-timeout: 3000
      packages:
        trust-all: true #消息支持传输及转换所有序列化对象，否则仅String
        #trusted:
      #pool:
          #enabled: true
          #expiry-timeout: 0
          #idle-timeout: 3000
          #max-connections: 100
          #reconnect-on-exception: true