# 代理的host  
httpclient.config:
    proxyHost: xxx.xx.xx.xx  
    # 代理端口  
    proxyPort: 8080  
    # 连接超时或异常重试次数  
    retryTime: 3  
    # 长连接保持时间，单位为s  
    keepAliveTime: 30  
    # 连接池最大连接数  
    connMaxTotal: 20  
    maxPerRoute: 20  
    # 连接超时时间，单位ms  
    connectTimeout: 2000  
    # 请求超时时间  
    connectRequestTimeout: 2000  
    # sock超时时间  
    socketTimeout: 2000  
    # 连接存活时间，单位s  
    timeToLive: 60 