#spring
spring:
  mail:
    host: smtp.126.com
    username: mail #
    password: password #
    properties: 
      mail:
        smtp:
          auth: true
          starttls: 
            enable: true
            required: true