# Logging
logging:
  level: 
    com.example.demo: debug
    
# Spring
spring:
  # RabbitMQ
  rabbitmq:
    host: localhost
    port: 5672
    password: guest
    username: guest
    listener:
      simple:
        concurrency: 2 #最小消息监听线程数
        max-concurrency: 2 #最大消息监听线程数