#spring
spring:
  datasource:
    url: jdbc:h2:mem:test;AUTO_RECONNECT=TRUE;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: root
    password: 123456
  jpa:
    properties:
      hibernate:
        hbm2ddl.auto: create-drop
        show_sql: true #显示转换的sql
  cache.jcache.config: classpath:ehcache.xml
  
#logger
logging:
  level:
    org: off
    com: off
    com.example.demo: debug
    org.hibernate.SQL: debug

# ＝＝ 说明 ＝＝
# [jpa.properties.hibernate.hbm2ddl.auto:]
# validate     加载hibernate时，验证创建数据库表结构
# create       每次加载hibernate，重新创建数据库表结构，这就是导致数据库表数据丢失的原因。
# create-drop  加载hibernate时创建，退出是删除表结构
# update       加载hibernate自动更新数据库结构